{
 "title": "NTP",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Total NTP clients",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(ntpserver_data{alias=\"server\"})"
    }
   ]
  },
  {
   "title": "Stratum",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "node_ntp_stratum" }
   ]
  },
  {
   "title": "NTP Clients",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ntpserver_data{alias=\"server\",ntpprotocol=\"1\"}",
     "legendFormat": "NTPv1"
    },
    {
     "expr": "ntpserver_data{alias=\"server\",ntpprotocol=\"2\"}",
     "legendFormat": "NTPv2"
    },
    {
     "expr": "ntpserver_data{alias=\"server\",ntpprotocol=\"3\"}",
     "legendFormat": "NTPv3"
    },
    {
     "expr": "ntpserver_data{alias=\"server\",ntpprotocol=\"4\"}",
     "legendFormat": "NTPv4"
    },
    {
     "expr": "ntpserver_data{alias=\"server\",ntpprotocol=\"0\"}",
     "legendFormat": "Unknown"
    }
   ]
  },
  {
   "title": "NTP offset",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "node_ntp_offset_seconds" }
   ]
  }
 ]
}